# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-13 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import webcore.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About_website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='Sample Title', max_length=80)),
                ('slug', models.SlugField(default='sample_title', unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('content', models.TextField(default='Sample Content')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='website_logo')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=models.SET(webcore.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='Sample Title', max_length=80)),
                ('slug', models.SlugField(default='sample_title', unique=True)),
                ('desc', models.CharField(max_length=60)),
                ('btn_link', models.URLField()),
                ('btn_title', models.CharField(max_length=18)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='Sample Title', max_length=80)),
                ('slug', models.SlugField(default='sample_title', unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=models.SET(webcore.models.get_sentinel_user), related_name='category_creator', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='webcore.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Contacted_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Sample Subject', max_length=30)),
                ('email', models.EmailField(default='example@domain.ext', max_length=254)),
                ('content', models.TextField(default='Sample Message Content')),
            ],
        ),
        migrations.CreateModel(
            name='EmailCampaignCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(default='sample_title', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcore.EmailCampaignCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailMarketingSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=False)),
                ('subscriptions', models.ManyToManyField(to='webcore.EmailCampaignCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(default='example@domain.ext', max_length=254, unique=True)),
                ('slug', models.SlugField(null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('action', models.CharField(default='NEWSLETTER', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='Sample Title', max_length=80)),
                ('slug', models.SlugField(default='sample_title', unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=1, on_delete=models.SET(webcore.models.get_sentinel_user), related_name='tag_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='Sample Title', max_length=80)),
                ('slug', models.SlugField(default='sample_title', unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=1, on_delete=models.SET(webcore.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='webcore/profile_photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webcore_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(default='Sample Title', max_length=80)),
                ('slug', models.SlugField(default='sample_title', unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('content', models.TextField(default='Sample Web Page Content')),
                ('author', models.ForeignKey(default=1, on_delete=models.SET(webcore.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
