# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0002_auto_20170103_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='emailverification',
            name='last_name',
        ),
        migrations.AddField(
            model_name='emailverification',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
