# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0003_auto_20170104_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
