# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0005_about_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
