# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import webcore.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webcore', '0006_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(default=webcore.models.get_waittime)),
                ('title', models.CharField(default='Sample Title', max_length=80, unique=True)),
                ('slug', models.SlugField(default='sample_title', unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
                ('author', models.ForeignKey(default=1, on_delete=models.SET(webcore.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webcore.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Contacted_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Sample Subject', max_length=30)),
                ('email', models.EmailField(default='example@domain.ext', max_length=254)),
                ('content', models.TextField(default='Sample Message Content')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(default=webcore.models.get_waittime)),
                ('title', models.CharField(default='Sample Title', max_length=80, unique=True)),
                ('slug', models.SlugField(default='sample_title', unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(default=1, on_delete=models.SET(webcore.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WebProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='webcore/profile_photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='webcore_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WebsitePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('published_on', models.DateTimeField(default=webcore.models.get_waittime)),
                ('title', models.CharField(default='Sample Title', max_length=80, unique=True)),
                ('slug', models.SlugField(default='sample_title', unique=True)),
                ('draft', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('content', models.TextField(default='Sample Web Page Content')),
                ('author', models.ForeignKey(default=1, on_delete=models.SET(webcore.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='about_website',
            name='about',
        ),
        migrations.RemoveField(
            model_name='about_website',
            name='email',
        ),
        migrations.RemoveField(
            model_name='about_website',
            name='name',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='created',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='emailmarketingconfirmed',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emailmarketingsignup',
            name='created',
        ),
        migrations.RemoveField(
            model_name='emailmarketingsignup',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='about_website',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='about_website',
            name='author',
            field=models.ForeignKey(default=1, on_delete=models.SET(webcore.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='about_website',
            name='content',
            field=models.TextField(default='Sample Content'),
        ),
        migrations.AddField(
            model_name='about_website',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about_website',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='about_website',
            name='published_on',
            field=models.DateTimeField(default=webcore.models.get_waittime),
        ),
        migrations.AddField(
            model_name='about_website',
            name='slug',
            field=models.SlugField(default='sample_title', unique=True),
        ),
        migrations.AddField(
            model_name='about_website',
            name='title',
            field=models.CharField(default='Sample Title', max_length=80, unique=True),
        ),
        migrations.AddField(
            model_name='about_website',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='banner',
            name='published_on',
            field=models.DateTimeField(default=webcore.models.get_waittime),
        ),
        migrations.AddField(
            model_name='banner',
            name='slug',
            field=models.SlugField(default='sample_title', unique=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailmarketingconfirmed',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmarketingconfirmed',
            name='published_on',
            field=models.DateTimeField(default=webcore.models.get_waittime),
        ),
        migrations.AddField(
            model_name='emailmarketingconfirmed',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='emailmarketingsignup',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmarketingsignup',
            name='published_on',
            field=models.DateTimeField(default=webcore.models.get_waittime),
        ),
        migrations.AddField(
            model_name='emailmarketingsignup',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='about_website',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about_website',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='website_logo'),
        ),
        migrations.AlterField(
            model_name='about_website',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(default='Sample Title', max_length=80, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
