# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0008_auto_20161114_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='action',
            field=models.CharField(default='NEWSLETTER', max_length=15),
        ),
    ]
