# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcore', '0004_userprofile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='website_logo')),
                ('about', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
